### ISSUE TITLE
Version Checker

### ISSUE THREAD

**Issue by ghost** [IcosphereIndustries/IslandCustomized#3]
Add a silly little version checker for the mod to let people know that "hey, the mod is outdated!!! you should probably update it!!!"

**Comment by ghost** [comment]
Will work on it tomorrow EST if Candycup doesn't do it by then (please don't I want to actually contribute to the mod and not only the treasure map)

**Comment by Karkkikuppi** [comment]
alright i'll leave this to you lol

**Comment by ghost** [comment]
finished in latest commit
