### ISSUE TITLE
remove custom defeat titles from battle box

### ISSUE THREAD

**Issue by Karkkikuppi** [IcosphereIndustries/IslandCustomized#7]
battle box doesn't use treasuremap's default titles

**Comment by Karkkikuppi** [comment]
clarification: defeat titles don't work

**Comment by ghost** [comment]
Defeat titles don't work in Battle Box because Battle Box doesn't use the "Elimination!" title

**Comment by hypeoh** [comment]
hi guys

**Comment by hypeoh** [comment]
hi guys

**Comment by Karkkikuppi** [comment]
Hold on, does bb even have defeat titles? When i lose a game i just get the regular "Game Over!" title, and that triggers the Game Over event. Issue should be changed to "remove custom defeat titles from bb"

**Comment by ghost** [comment]
fixed as of https://github.com/IcosphereIndustries/IslandCustomized/commit/16ba47f09c45741e28078f2883baaa19a75a413d
