### ISSUE TITLE
tgttos message replacements don't work

### ISSUE THREAD

**Issue by Karkkikuppi** [IcosphereIndustries/IslandCustomized#8]
tgttos doesn't use treasuremap's default titles

**Comment by Karkkikuppi** [comment]
clarification: defeat titles don't work

**Comment by Karkkikuppi** [comment]
actually idk what i'm on about like none of the messages work

**Comment by ghost** [comment]
Seems to be fixed now actually.

**Comment by Karkkikuppi** [comment]
Same as with #7. There are no defeat messages to be replaced. There are, however, round finish titles that we could replace...

![image](https://github.com/IcosphereIndustries/IslandCustomized/assets/64687000/916d99af-3f86-4f6d-9c3f-6f0fe74d4c0f)

**Comment by Karkkikuppi** [comment]
so either we check if we lost by checking the subtitles of the title or we just remove defeat titles from the tgttos config

**Comment by ghost** [comment]
fixed as of https://github.com/IcosphereIndustries/IslandCustomized/commit/16ba47f09c45741e28078f2883baaa19a75a413d
